{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Release.Name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: secure-coding-portal
type: Opaque

{{ if $secret -}}
data:
  db_pass: {{ $secret.data.db_pass }}
  challenge_master_salt: {{ $secret.data.challenge_master_salt }}
  enc_key: {{ $secret.data.enc_key }}
  enc_key_iv: {{ $secret.data.enc_key_iv }}
{{ else -}}
stringData:
  db_pass: {{ randAlphaNum 16 | quote }}
  challenge_master_salt: {{ randAlphaNum 16 | quote }}
  enc_key: {{ randAlphaNum 16 | quote }}
  enc_key_iv: {{ randAlphaNum 16 | quote }}
{{ end }}