apiVersion: v1
kind: Service
metadata:
  name: secure-coding-portal-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: secure-coding-portal-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secure-coding-portal-mysql
spec:
  selector:
    matchLabels:
      app: secure-coding-portal-mysql
  serviceName: secure-coding-portal-mysql
  template:
    metadata:
      labels:
        app: secure-coding-portal-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: secure-coding-portal-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secure-coding-portal
              key: db_pass
        - name: MYSQL_DATABASE
          value: scpdb
        - name: MYSQL_USER
          value: scpdbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secure-coding-portal
              key: db_pass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /opt/dojo/mysql
          type: ""
        name: data

