apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-target
  namespace: dojo
  labels:
    app: training-target
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-target
  template:
    metadata:
      name: training-target
      labels:
        app: training-target
    spec:
      containers:
        - name: training-target
          ports:
            - containerPort: 8080
          env:
            - name: CHALLENGE_MASTER_SALT
              value: "supersecretmastersalt"
          image: registry.mgt.dragonfly-managed.services/docker/mantisec/insecure.inc
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: training-target-svc
  namespace: dojo
spec:
  selector:
    app: training-target
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: training-target-ing
  namespace: dojo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
    - host: target.mantisec.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: training-target-svc
                port:
                  number: 80
    - host: target.dojo.mantisec.com.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: training-target-svc
                port:
                  number: 80

  tls:
  - hosts:
    - target.mantisec.online
    - target.dojo.mantisec.com.au
    secretName: target-dojo-cert